name: Format Check

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  format-check:
    name: Check Code Formatting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Prettier
        run: npm install -g prettier

      - name: Install Clang Format
        uses: jidicula/clang-format-action@v4.15.0
        with:
            clang-format-version: '20'
            check-path: 'src'

      - name: Run Prettier
        run: prettier --check "**/*.{js,ts,json,md,yaml}"
