name: Format Check

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  format-check:
    name: Check Code Formatting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v4

      - name: Install Dependencies
        run: npm ci

      - name: Install Clang Format
        uses: jidicula/clang-format-action@v4.15.0
        with:
            clang-format-version: '20'
            check-path: 'src'

      - name: Run Prettier
        run: ./node_modules/.bin/prettier --check 'src/**/*.{js,json,css,html}' platformio.ini package.json README.md vite.config.mjs tailwind.config.js
